### ISSUE TITLE
El Capitan and Safari 9 combination throwing invalid OS/brower combination error. 

### ISSUE THREAD

**Issue by shashikantjagtap** [browserstack/automate-ruby-samples#3]
El Capitan and Safari 9 combination throwing invalid OS/brower combination error. 

Capability I am trying is 

    "browser: "Safari",
    "browser_version": "9.0",
    "os": "OS X",
    "os_version": "El Capitan"

Error I am getting 

              OS/Browser combination invalid: {"browser"=>"Safari", "language"=>"Ruby", "os"=>"OS X", "project"=>"Programmes", "os_version"=>"El Capitan", "browserstack.video"=>"true", "browserstack.debug"=>true, "browserName"=>"Safari", "browser_version"=>"9.0", "acceptSslCert"=>false} (Selenium::WebDriver::Error::UnknownError)

Let me know if I am missing anything. I can launch VM for manual testing though !
Can you please look into this if it's an issue ?

**Comment by nidhimj22** [comment]
caps['browser'] = 'Safari'
caps['browser_version'] = '9.0'
caps['os'] = 'OS X'
caps['os_version'] = 'El Capitan'

This works. Further, you can use https://www.browserstack.com/automate/ruby#setting-os-and-browser for seeing how you can mention capabilities for different OS, browser versions.
